### ISSUE TITLE
unable to render raw image string for qrcode

### ISSUE THREAD

**Issue by romunov** [hudora/huBarcode#24]
I'm having trouble render an image of QR code (works for DataMatrix).

``` Python
from hubarcode.qrcode import QRCodeEncoder

qr = QRCodeEncoder("m103")
qr_raw_ascii = qr.get_ascii()
print(qr_raw_ascii) # works
qr_raw_img = qr.get_imagedata()
print(qr_raw_img) # prints error listed below
```

```
Traceback (most recent call last):
  File "D:/py_workspace/otf_barcode/source/test", line 6, in <module>
    qr_raw_img = qr.get_imagedata()
  File "C:\Python27\lib\site-packages\hubarcode\qrcode\__init__.py", line 44, in get_imagedata
    imagedata = qrc.get_imagedata(cellsize)
  File "C:\Python27\lib\site-packages\hubarcode\qrcode\renderer.py", line 53, in get_imagedata
    img = self.get_pilimage(cellsize)
  File "C:\Python27\lib\site-packages\hubarcode\qrcode\renderer.py", line 33, in get_pilimage
    self.add_border(colour=0, width=4)
  File "C:\Python27\lib\site-packages\hubarcode\qrcode\renderer.py", line 26, in add_border
    for i in range(0, self.mtx_size - (width * 2))]
IndexError: list index out of range
```

Am I doing something wrong?

**Comment by mdornseif** [comment]
I have no idea. We never used QRcode in production.
